name = "lightroom-worker"
main = "src/worker.ts"
compatibility_date = "2024-01-16"

# Variable bindings
[vars]
ADOBE_REDIRECT_URI = "https://lightroom-worker.bot-7f9.workers.dev/auth/callback"
DEPLOY_HOOK_URL = ""

# KV namespaces
[[kv_namespaces]]
binding = "lightroom-worker-ADOBE_OAUTH_TOKENS"
id = "b4606e3118c94b25a0b99ff9815fc8ca"

[[kv_namespaces]]
binding = "lightroom-worker-ADOBE_API_CREDENTIALS"
id = "9799cc02d7af4843b133e32f4b937e5e"

[observability]
enabled = true
head_sampling_rate = 1